// import Head from 'next/head'
// import { useEffect } from "react";

// import React from 'react'
// import Image from 'next/image'
// import Link from 'next/link'

// export default function Staking() {

//   return (
//     <div className="font-['Montserrat'] hide-scrollbar text-white bg-black h-screen w-screen overflow-y-scroll">

//       <Head>
//         <title>$BORED Staking Platform</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//         <meta
//           name="description"
//           content="$BORED staking platform"
//         />
//       </Head>

//       <div className='Section1 h-full w-11/12 mx-auto pb-14' id='home'>
//         <div className='h-full w-full flex flex-col justify-center items-center'>
//           <div className='w-11/12 bg-black border-2 items-center lg:flex lg:justify-between  my-5 rounded-lg p-3 lg:p-4 font-extralight shadow-md shadow-primary lg:shadow-xl lg:shadow-primary overflow-y-hidden'>
//             <h1 className='font-semibold'>$APE staked by DAO: 10,280 $APE (</h1>
//             <h1 className='font-semibold'>$BORED staking pool: 37.81%</h1>
//           </div>
//           <div className='w-11/12 flex flex-col relative justify-center items-center bg-black border-2 my-5 rounded-lg p-2 lg:p-4 font-extralight shadow-md shadow-primary lg:shadow-xl lg:shadow-primary overflow-y-hidden'>
//             <video preload='auto' loop autoPlay muted className='w-11/12 sm:w-1/3' >
//               <source src="/boredsmall.mp4" type='video/mp4' />
//             </video>
//             <img src="logo.png" alt="logo" className='hidden md:block absolute bottom-7 right-7 w-20' />

//             <h1 className='text-center mb-4 lg:text-xl font-semibold'>Total staked: 64,056,790 $bored</h1>
//             <div className='w-11/12 sm:w-1/2 xl:w-1/3 flex justify-evenly'>
//               <button className='py-2 w-2/5 lg:py-4 mb-6 rounded-full text-sm lg:text-lg font-medium border-white border-2 shadow-lg shadow-primary transition-all duration-300 active:bg-white active:text-black active:border-black lg:hover:bg-white lg:hover:text-black lg:hover:border-black'>
//                 Claim $APE
//               </button>
//               <button className='py-2 w-2/5 lg:py-4 mb-6 rounded-full text-sm lg:text-lg font-medium border-white border-2 shadow-lg shadow-primary transition-all duration-300 active:bg-white active:text-black active:border-black lg:hover:bg-white lg:hover:text-black lg:hover:border-black'>
//                 Withdraw
//               </button>
//             </div>
//           </div>
//         </div>
//       </div>

//       <div className='Section2 h-full w-11/12 mx-auto border-t-2 my-0 pb-14'>
//         <div className='h-full w-full flex flex-col justify-center items-center'>

//           <div className='w-11/12 flex flex-col lg:flex-row lg:justify-start justify-center items-center bg-black border-2 my-5 rounded-lg p-2 lg:p-5 font-extralight shadow-md shadow-primary lg:shadow-xl lg:shadow-primary overflow-y-hidden'>
//             <img src="BAYC1.jpg" alt="bayc" className='hidden lg:block w-38 rounded-lg mr-5' />
//             <div>
//               <h1 className='text-xl font-semibold lg:text-4xl'>BAYC</h1>
//               <p className='text-lg font-medium mb-2 lg:text-2xl'>Staked: #3273</p>
//               <p className='text-md font-extralight lg:text-xl lg:font-light lg:w-3/4'>Each BAYC is paired with 10,094 $APE staked - yield will be distributed to holders as staking rewards</p>
//             </div>
//           </div>
//           <div className='w-11/12 flex flex-col lg:flex-row lg:justify-start justify-center items-center bg-black border-2 my-5 rounded-lg p-2 lg:p-5 font-extralight shadow-md shadow-primary lg:shadow-xl lg:shadow-primary overflow-y-hidden'>
//             <img src="mutant 1.jpg" alt="mayc" className='hidden lg:block w-38 rounded-lg mr-5' />
//             <div>
//               <h1 className='text-xl font-semibold lg:text-4xl'>MAYC</h1>
//               <p className='text-lg font-medium mb-2 lg:text-2xl'>Staked: #3273</p>
//               <p className='text-md font-extralight lg:text-xl lg:font-light lg:w-3/4'>Each MAYC is paired with 2,042 $APE staked - yield will be distributed to holders as staking rewards</p>
//             </div>
//           </div>
//           <div className='w-11/12 flex flex-col lg:flex-row lg:justify-start justify-center items-center bg-black border-2 my-5 rounded-lg p-2 lg:p-5 font-extralight shadow-md shadow-primary lg:shadow-xl lg:shadow-primary overflow-y-hidden'>
//             <img src="bakc1.png" alt="bakc" className='hidden lg:block w-38 rounded-lg mr-5' />
//             <div>
//               <h1 className='text-xl font-semibold lg:text-4xl'>BAKC</h1>
//               <p className='text-lg font-medium mb-2 lg:text-2xl'>Staked: #856</p>
//               <p className='text-md font-extralight lg:text-xl lg:font-light lg:w-3/4'>Each BAKC is paired with 856 $APE staked - yield will be distributed to holders as staking rewards</p>
//             </div>
//           </div>
//         </div>
//       </div>



//       <footer className="w-11/12 py-0 bg-black mx-auto overflow-hidden">
//         <footer className="w-11/12 pt-2 bg-black bottom-0 font-medium border-t-2 border-t-white fixed flex justify-between">
//           <p className='mb-3'>Bored Token</p>
//           <div>
//             <Link href="/" className='mb-3 mr-4 transition-all duration-200 hover:text-primary'>Home</Link>
//             <Link href="#socials" className='mb-3 mr-4 transition-all duration-200 hover:text-primary'>Socials</Link>
//             <Link href="/staking" className='mb-3 transition-all duration-200 hover:text-primary'>Stake</Link>
//           </div>
//         </footer>
//       </footer>


//     </div >
//   )
// }
